### PR TITLE
Added danger and question symbols

### PR DESCRIPTION
**Pull request by Berkmann18**
I felt it that this package was missing some other log symbols such as the question mark one and the danger skull one (although that one isn't on code page 437 and don't have any "danger"/"death" related icons) so I opened this PR.

### CODE REVIEW

**Comment by Berkmann18** [comment]
It seems that there's something wrong on `v4` since both commits succeeded on both `v6` and `v8` but I notice this error on the `v4` build:
```bash
> xo && ava
/home/travis/build/sindresorhus/log-symbols/node_modules/xo/cli-main.js:115
const {input, flags: opts} = cli;
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/sindresorhus/log-symbols/node_modules/xo/cli.js:15:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
It seems that this error is relevant to `xo` and not this package.

**Comment by sindresorhus** [comment]
What's the use-cases for these new icons?

**Comment by sindresorhus** [comment]
> (although that one isn't on code page 437 and don't have any "danger"/"death" related icons)

The whole point of this package is to have good fallbacks for all the icons.

**Comment by Berkmann18** [comment]
Fair enough.

**Pull request closed without merging**
