### PR TITLE
Modify Info Symbol Because Original Shows Only A Block

### PR DESCRIPTION
**Pull request by clemtrek**

### CODE REVIEW

**Comment by sindresorhus** [comment]
It works fine where I've tried it. Not really enough information in this PR to do anything about it.

**Comment by clemtrek** [comment]
Sorry, I was in a bit of _hurry_

When I ran this module at https://npm.runkit.com/log-symbols. It showed nothing for the info symbol. Therefore, I created this pull request.

> My First Pull Request.

>

**Comment by clemtrek** [comment]
@sindresorhus , Link https://runkit.com/embed/r8hs3q2w1nub

**Comment by sindresorhus** [comment]
It works fine there for me. And this module is meant for the CLI, not the browser.

**Pull request closed without merging**
