### PR TITLE
Ci

### PR DESCRIPTION
**Pull request by gucong3000**
- #6 
- split module
- add AppVeyor service

### CODE REVIEW

**Comment by gucong3000** [comment]
[CircleCI](https://circleci.com/gh/gucong3000/log-symbols/2?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
[Appveyor](https://ci.appveyor.com/project/gucong3000/log-symbols/build/1.0.5)
[Travis CI](https://travis-ci.org/gucong3000/log-symbols/builds/254762213?utm_source=github_status&utm_medium=notification)

**Comment by sindresorhus** [comment]
I don't really want to have AppVeyor run here. It's slow and flaky. And splitting this tiny module into multiple files doesn't have much benefit.

**Comment by gucong3000** [comment]
> It's slow and flaky.
@sindresorhus I totally agree with you.

**Comment by sindresorhus** [comment]
I'm happy to add the browser support in a separate focused PR though :)

**Comment by gucong3000** [comment]
>I'm happy to add the browser support in a separate focused PR though :)

#8

**Pull request closed without merging**
