### PR TITLE
judge font `Segoe UI Emoji` exists

### PR DESCRIPTION
**Pull request by gucong3000**

### CODE REVIEW

**Comment by sindresorhus** [comment]
This only checks if the font exists on the user's system, not whether it's actually used.

**Comment by gucong3000** [comment]
It's not 100% accurate, but it's more reliable than judging the version number.

**Comment by SamVerschueren** [comment]
Can you explain in more detail what you're doing? I looked it up myself and found the [Code Page Identifiers](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx). What makes you think that those identifiers use the Segoe UI font?

**Comment by gucong3000** [comment]
> I found that in a Western-language version of Windows, emoji is not displayed under the default configuration.

#11

**Comment by gucong3000** [comment]
I tried windows10 Simplified Chinese version

**Comment by gucong3000** [comment]
> What makes you think that those identifiers use the Segoe UI font?

I tried windows10 Simplified Chinese version.
Other code is inferred.

**Comment by sindresorhus** [comment]
> I found that in a Western-language version of Windows, emoji is not displayed under the default configuration.

That's just speculation though unless you can link to a source?

**Comment by sindresorhus** [comment]
I'm not sure I want this. Doing a sync spawn on startup is very bad performance-wise. I think it would be easier and better to just revert https://github.com/sindresorhus/log-symbols/commit/2c129440922109554f2337023530c63fc180bc8d. It's clear that Windows is not universally Unicode ready yet.

**Comment by kevva** [comment]
>  I think it would be easier and better to just revert 2c12944.

+1. Spawning a process also makes it more prone to errors unless handled correctly. Especially on Windows. With that and the negative performance impact in mind, I don't think there's super much to gain here.

**Pull request closed without merging**
